---
# file: roles/common/tasks/main.yml

- name: accept Oracle license
  shell: "echo oracle-java{{ oracle_java_version }}-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections"
  changed_when: no
  become: true

- name: ensure Java is installed
  apt:
    name="oracle-java{{ oracle_java_version }}-installer"
    state={{ oracle_java_state }}
    cache_valid_time={{ oracle_java_cache_valid_time }}
    update_cache=yes
  register: oracle_java_task_apt_install
  become: true

- name: set Java version as default
  apt:
    name="oracle-java{{ oracle_java_version }}-set-default"
    state=latest
  register: oracle_java_task_set_default
  when: oracle_java_set_as_default
  become: true